apiVersion: v1
kind: Service
metadata:
 name: database
spec:
 ports:
 - port: 3306
   targetPort: 3306
   proticol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
 name: database
subsets:
- addresses:
- ip: 127.0.0.1
 ports:
 - port: 3306
